language: node_js
node_js:
  - "9.11.1"
cache:
  directories:
    - "node_modules"
script:
    - yarn lint
    - yarn unit
    - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: bde7dd9765f37bf959147d24e4d0ae83e506270b
  local_dir: dist
  on:
    branch: master
